services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: school-supplies-exchange-backend
    container_name: school_supplies_exchange-backend
    restart: unless-stopped
    ports:
      - "10000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/storage
